server {
    listen 8099;
    root /www;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /runtime-config.js {
        add_header Cache-Control "no-store";
    }
}
